# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
anaconda=custom=py27_0
backports_abc=0.4=py27_0
bokeh=0.11.1=py27_0
decorator=4.0.9=py27_0
flask=0.10.1=py27_1
futures=3.0.3=py27_0
ipython=4.1.2=py27_0
ipython_genutils=0.1.0=py27_0
itsdangerous=0.24=py27_0
jinja2=2.8=py27_0
markupsafe=0.23=py27_0
mkl=11.3.1=0
ncurses=5.9=0
numpy=1.10.4=py27_1
openssl=1.0.2g=0
pandas=0.18.0=np110py27_0
path.py=8.1.2=py27_1
pexpect=3.3=py27_0
pickleshare=0.5=py27_0
pip=8.1.1=py27_0
python=2.7.11=0
python-dateutil=2.5.1=py27_0
pytz=2016.2=py27_0
pyyaml=3.11=py27_1
readline=6.2=2
requests=2.9.1=py27_0
setuptools=20.3=py27_0
simplegeneric=0.8.1=py27_0
singledispatch=3.4.0.3=py27_0
six=1.10.0=py27_0
sqlite=3.9.2=0
ssl_match_hostname=3.4.0.2=py27_0
tk=8.5.18=0
tornado=4.3=py27_0
traitlets=4.2.1=py27_0
werkzeug=0.11.4=py27_0
wheel=0.29.0=py27_0
yaml=0.1.6=0
zlib=1.2.8=0
